// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import "./BaseFacet.sol";
import "../libraries/LibAppStorage.sol";
import "../interfaces/IDFLToken.sol";

    error SwapOutbound__ZeroAmount();
    error SwapOutbound__DestinationNotConfigured();
    error SwapOutbound__AlreadyRefunded();
    error SwapOutbound__InvalidSignature();

/**
 * @title Bridge Outbound Facet
 * @author 0xAvp
 * @notice Handles user-facing source-chain actions including initiating swaps and processing refunds.
 * @dev Inherits from BaseFacet. Integrates lightweight ECDSA verification and Burn-and-Mint logic.
 */
contract SwapOutboundFacet is BaseFacet {

    event SwapToNativeInitiated(bytes32 indexed swapId, address indexed user, uint256 amount, uint64 indexed destChainId, uint256 nonce);
    event SwapRefunded(bytes32 indexed swapId, address indexed user, uint256 amount);

    /**
     * @notice Initiates a cross-chain swap by burning DFL tokens on the source chain to receive native tokens on destination.
     * @dev Generates a unique swapId using a user-specific nonce, burns tokens, and emits SwapToNativeInitiated.
     * @param _amount The amount of DFL tokens to swap (in wei).
     * @param _destChainId The target network chain identifier (chain selector).
     */
    function swapDFLToNative(uint256 _amount, uint64 _destChainId) external whenNotPaused nonReentrant {
        if (_amount == 0) revert SwapOutbound__ZeroAmount();

        LibAppStorage.AppStorage storage s = LibAppStorage.layout();

        // 1. Ensure the destination pool is configured and connected
        if (s.poolConfigs[_destChainId].peerBridge == address(0)) {
            revert SwapOutbound__DestinationNotConfigured();
        }

        // 2. Fetch and increment user nonce to prevent unique swapId collisions
        uint256 nonce = s.swapNonces[msg.sender];
        s.swapNonces[msg.sender] = nonce + 1;

        // 3. Generate a mathematically unique swap identifier
        bytes32 swapId = keccak256(abi.encodePacked(
            msg.sender,
            _destChainId,
            _amount,
            nonce,
            block.chainid
        ));

        emit SwapToNativeInitiated(swapId, msg.sender, _amount, _destChainId, nonce);

        // 4. Burn DFL tokens from the user's wallet
        IDFLToken(s.dflToken).burnFrom(msg.sender, _amount);
    }

    /**
     * @notice Reclaims DFL tokens on the source chain using an authorized relayer signature.
     * @dev Verifies that the swap was cancelled on the destination chain, reconstructs the EIP-191 signature,
     *      and mints the DFL tokens back to the user.
     * @param _swapId The unique identifier of the initiated swap.
     * @param _amount The original burned amount of DFL tokens (in wei).
     * @param _destChainId The target network chain identifier of the original swap.
     * @param _nonce The user nonce used when initiating the swap.
     * @param _signature The cryptographic signature generated by the authorized relayer.
     */
    function refundDFL(
        bytes32 _swapId,
        uint256 _amount,
        uint64 _destChainId,
        uint256 _nonce,
        bytes calldata _signature
    ) external whenNotPaused nonReentrant {
        LibAppStorage.AppStorage storage s = LibAppStorage.layout();

        // 1. Guard against double-refund attacks
        if (s.swapStates[_swapId].refunded) {
            revert SwapOutbound__AlreadyRefunded();
        }

        // 2. Reconstruct the original hashed parameters to verify intent
        bytes32 messageHash = keccak256(abi.encodePacked(
            _swapId,
            _amount,
            _destChainId,
            _nonce,
            "REFUND",
            block.chainid // Binding the refund to the current source chain ID
        ));

        // 3. Format as EIP-191 standard signed message
        bytes32 ethSignedMessageHash = keccak256(abi.encodePacked(
            "\x19Ethereum Signed Message:\n32",
            messageHash
        ));

        // 4. Recover the signer and verify it matches our authorized relayer hot wallet
        address signer = _recoverSigner(ethSignedMessageHash, _signature);
        if (signer != s.relayer) {
            revert SwapOutbound__InvalidSignature();
        }

        // 5. Update state to finalized and mint tokens back to the user
        s.swapStates[_swapId].refunded = true;

        emit SwapRefunded(_swapId, msg.sender, _amount);

        IDFLToken(s.dflToken).mint(msg.sender, _amount);
    }

    /**
     * @notice Internal helper to recover the signer of an EIP-191 message hash.
     * @dev Splits the signature into r, s, v components via gas-efficient inline assembly.
     * @param _ethSignedMessageHash The formatted EIP-191 message hash.
     * @param _signature The raw 65-byte signature.
     * @return The recovered address, or address(0) if invalid.
     */
    function _recoverSigner(bytes32 _ethSignedMessageHash, bytes calldata _signature) internal pure returns (address) {
        if (_signature.length != 65) return address(0);

        bytes32 r;
        bytes32 s;
        uint8 v;

        // Assembly split is significantly more gas-efficient than high-level slicing
        assembly {
            r := calldataload(_signature.offset)
            s := calldataload(add(_signature.offset, 32))
            v := byte(0, calldataload(add(_signature.offset, 64)))
        }

        return ecrecover(_ethSignedMessageHash, v, r, s);
    }
}